// Backwards-compatible re-exports.
//
// The reference data now lives in `./applicationData`, rewritten after research
// into the 2026-27 Common App / UC / UCAS requirements. Pages and components
// import from here, so the original import paths keep working unchanged.

export {
  APPLICATION_CYCLES,
  CURRENT_CYCLE,
  PLATFORMS,
  PLATFORM_LABELS,
  PLATFORM_VALUES,
  PLATFORM_REQUIREMENTS,
  COMMON_APP_PROMPTS,
  COMMON_APP_PERSONAL_STATEMENT,
  COMMON_APP_AUXILIARY,
  UC_PIQS,
  UC_RULES,
  UCAS_QUESTIONS,
  UCAS_RULES,
  UCAS_PROMPT_TEXT,
  US_ROUNDS,
  UK_ROUNDS,
  UK_UNIVERSITY_NOTES,
  ESSAY_TYPES,
  ESSAY_STATUSES,
  findUKUniversityNote,
  normalizeUniversityName,
  universityMatchKey,
  universityNamesMatch,
  findKnowledgeRecord,
  getUniversityPlatform,
  doesPlatformShareEssays,
  buildSharedEssayPlan,
  essaysApplicableToUniversity,
  isSharedEssay,
  isCommonEssay,
  isUniversitySpecific,
  limitUnitFor,
  measureEssay,
  formatLimit,
  resolvedEssayLimit,
  ucasQuestionFor,
  isUcasQuestion,
  isLegacyUcasStatement,
  ucasQuestionsFrom,
  ucasCharacterBudget,
  commonAppPromptsInText,
  isAmbiguousCommonAppPrompt,
  isCommonAppPersonalStatement,
  chosenCommonAppPrompt,
} from './applicationData';
