// Application roadmap templates for US and UK universities.
//
// The original US template hard-coded "Japanese grading scale" and "Japanese
// educational system" in three tasks, which is actively wrong advice for
// anyone not in the Japanese system — and the AI repeats it back during the
// holistic review. Everything here is now applicant-neutral, with the
// applicant-specific explanation pushed into a task they can fill in.

export const roadmapTemplates = {
  US: [
    { category: "testing", title: "Confirm the test policy", description: "Check whether each school is test-optional, required, or test-flexible. Decide which sitting to report, and note any superscore or Score Choice rules that apply.", order: 1 },
    { category: "testing", title: "Send official scores", description: "Release SAT/ACT through the testing agency and English proficiency scores through IELTS/TOEFL. Verify each score arrives before the school's posted deadline — not just the application deadline.", order: 2 },
    { category: "academic_records", title: "Order official transcripts", description: "Request transcripts covering the full secondary record (grades 9 onward). Many schools require them to arrive directly from the school, submitted by the school, not by you.", order: 3 },
    { category: "academic_records", title: "Prepare a school-system explanation", description: "Write one page explaining your curriculum, how grading works, and what a reader needs to know to interpret your transcript correctly. This is the single most useful document for an international applicant, and it is often left out.", order: 4 },
    { category: "academic_records", title: "Predict or submit final grades", description: "If you sit IB, AP, A-levels or another qualification, confirm how predicted grades are submitted and in what format the school expects them.", order: 5 },
    { category: "application_platform", title: "Create the application account", description: "Set up the Common Application (or the UC, Coalition, or the school's own portal) and complete the biographical and family sections once — they are shared across every school on the platform.", order: 6 },
    { category: "application_platform", title: "Add each university to your list", description: "Add this university and read the questions in its profile on the platform. School-specific questions are NOT shared between schools — each one is written separately.", order: 7 },
    { category: "essays", title: "Write the shared personal statement", description: "One 250-650 word essay sent identically to every Common App school. It must contain no school-specific content. Pick the prompt that fits your story, not the one that sounds strongest.", order: 8 },
    { category: "essays", title: "Research this university", description: "Run a research report in the Knowledge Base: deadlines, admitted-student profile, the exact supplement prompts, and what each prompt is actually testing. Do this before writing a word of the supplements.", order: 9 },
    { category: "essays", title: "Write the school-specific supplements", description: "Each supplement is read alongside the personal statement. Repeating a story you already told is the most common way to lose an admission — show something the personal statement did not.", order: 10 },
    { category: "essays", title: "Run an admissions review on every essay", description: "Have each essay reviewed against its own prompt, then apply the edits. Check the length limit on the school's own portal, not just here.", order: 11 },
    { category: "recommendations", title: "Request recommendations", description: "Ask for a mix of subjects and contexts. Give every recommender your resume, your activity list, and a short description of the school and programme so they can write about you specifically rather than generically.", order: 12 },
    { category: "recommendations", title: "Submit the school report / counselor recommendation", description: "Complete the school report, and give your counselor your school-system explanation sheet — without it, the school report is a disadvantage for an international student.", order: 13 },
    { category: "recommendations", title: "Follow up before the deadline", description: "Contact every recommender 3-4 weeks out. Recommenders who do not know the deadline do not submit on time.", order: 14 },
    { category: "financial", title: "Complete the financial aid forms", description: "Determine which forms apply (FAFSA, CSS Profile, and the school's own international form) and their deadlines. International applicants are often on a different calendar from domestic ones.", order: 15 },
    { category: "financial", title: "Research scholarships", description: "Identify need-based and merit scholarships open to international applicants. Note separate, earlier deadlines for scholarship consideration.", order: 16 },
    { category: "financial", title: "Prepare proof of funding", description: "Bank statements, sponsor documentation, or scholarship letters. Some countries require certification or a specific bank-issue date.", order: 17 },
    { category: "interview", title: "Prepare for an interview if offered", description: "Research the format, then practice answering questions about your essay, your interests, and why this specific school. Record yourself once and listen back.", order: 18 },
    { category: "portfolio", title: "Submit a portfolio if required", description: "Some programmes (arts, architecture, design, film) require a portfolio with their own format, size limit and deadline. Check before you assume the general application is enough.", order: 19 },
    { category: "submission", title: "Full read-through", description: "Re-read every field of the submitted application as an admissions officer would. Check dates, names, and consistency between your activities, your essay, and your recommendations.", order: 20 },
    { category: "submission", title: "Submit early", description: "Submit 3-5 days before the deadline. Watch the time zone: US deadlines are typically Eastern Time, not your local time.", order: 21 },
    { category: "post_submission", title: "Send updates if relevant", description: "If a major award, test score, or new activity lands after submission, check whether the school accepts updates and send them through the official channel.", order: 22 },
    { category: "post_submission", title: "Track your status", description: "Monitor the applicant portal for missing items. A missing document can invalidate an otherwise complete application.", order: 23 },
  ],

  UK: [
    { category: "application_platform", title: "Choose your five UCAS course choices", description: "UCAS allows a limited number of course choices, all for the same entry year. Choose courses in a related field: ONE personal statement is sent to every choice, so five unrelated subjects weaken the statement for all five.", order: 1 },
    { category: "application_platform", title: "Create your UCAS account", description: "Register on UCAS, complete the personal details and qualification history once, and check whether you need a tariff or reference sheet for your home qualification.", order: 2 },
    { category: "application_platform", title: "Check the deadline for each course", description: "Oxford, Cambridge, and all medicine, dentistry and veterinary courses close on 15 October 2026. Everything else closes on 13 January 2027. Applicants who miss the main deadline move into clearing, which is far less flexible.", order: 3 },
    { category: "testing", title: "Register for admissions tests", description: "Many courses require an admissions test: ESAT or TMUA for engineering, CSAT for computing, HAT or TSA for humanities or medicine. Book early — sittings fill up and each has its own registration deadline.", order: 4 },
    { category: "testing", title: "Send English proficiency scores", description: "Send IELTS, TOEFL or Duolingo directly from the test provider. Check the minimum overall score AND any per-component minimum, and confirm the score is inside its validity window.", order: 5 },
    { category: "academic_records", title: "Prepare your school reference", description: "Your school or referee writes a UCAS reference on the form UCAS provides. Give them your personal statement draft, your predicted grades, and a list of achievements — a reference with no context is generic and reads as such.", order: 6 },
    { category: "academic_records", title: "Confirm predicted grades", description: "If you sit IB, A-levels or an equivalent, your predicted grades are submitted through your school. Make sure they are accurate and submitted through the correct route for your country.", order: 7 },
    { category: "essays", title: "Write the UCAS personal statement — three questions", description: "Since 2026 entry UCAS asks three fixed questions in one 4,000-character statement (including spaces), with at least 350 characters per answer. Q1: why this course. Q2: how your studies prepared you. Q3: what you have done outside education. Never name a university. The same text goes to all five choices.", order: 8 },
    { category: "essays", title: "Keep the academic content high", description: "Oxford expects roughly 80% of the statement to be academic (about 800 of the 4,000 characters can be non-academic). Cambridge caps non-academic material at 20% of whichever answer it appears in. Draft to the tighter of those.", order: 9 },
    { category: "essays", title: "Check for extra statements", description: "Cambridge asks for an additional Cambridge-specific statement of up to 1,200 characters in My Cambridge Application, due 22 October 2026. Some universities and courses also ask for supplementary forms or written work.", order: 10 },
    { category: "recommendations", title: "Submit the academic reference", description: "Complete the reference form your school has been sent, and check UCAS has received it. A missing reference stops an application being considered even if everything else is perfect.", order: 11 },
    { category: "financial", title: "Confirm fees and funding", description: "Check the international tuition fee and whether there is any financial declaration form to complete. Oxford and Cambridge, for example, have their own financial application processes for some awards.", order: 12 },
    { category: "interview", title: "Prepare for interviews", description: "Oxford, Cambridge, Imperial and many other universities interview, and many courses also set a written work or pre-interview task. Find out what your specific course requires — it is not uniform across the university.", order: 13 },
    { category: "submission", title: "Submit before the deadline", description: "UCAS deadlines are 18:00 UK time on the day. Submit earlier — the system is busy near the deadline and a technical failure costs you the round.", order: 14 },
    { category: "post_submission", title: "Complete any additional questionnaires", description: "Oxford and Cambridge both require extra forms after UCAS submission. Missing these is a common reason a strong application is never read.", order: 15 },
    { category: "post_submission", title: "Track offers on UCAS", description: "Check UCAS for interview invitations, offers, and scholarship decisions. Respond to offers within the stated window.", order: 16 },
  ],
};